"""password hash column update

Revision ID: 2eacc386e84e
Revises: c9d79b9c28b9
Create Date: 2025-03-26 17:09:09.341999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eacc386e84e'
down_revision = 'c9d79b9c28b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
