"""updated user_id to class_id in tasks

Revision ID: c9d79b9c28b9
Revises: 95d6a53401ef
Create Date: 2025-03-21 17:40:26.614328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d79b9c28b9'
down_revision = '95d6a53401ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_tasks_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_class_id_classes'), 'classes', ['class_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_tasks_class_id_classes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
