"""added category and category_tasks table dropped user_classalso fixed foreignkey ref error

Revision ID: e2dfb2bde35c
Revises: e4ea27c74f1b
Create Date: 2025-03-21 15:19:37.116655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2dfb2bde35c'
down_revision = 'e4ea27c74f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_tasks_category_id_categories')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_category_tasks_task_id_tasks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_classes')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_classes_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_user_class_id_user_classes', type_='foreignkey')
        batch_op.drop_column('user_class_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_class_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_tasks_user_class_id_user_classes', 'user_classes', ['user_class_id'], ['id'])

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classes_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('user_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='fk_user_classes_class_id_classes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_classes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category_tasks')
    op.drop_table('categories')
    # ### end Alembic commands ###
